# Generated by Django 4.1.5 on 2023-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('original_url', models.CharField(max_length=2048)),
                ('short_url', models.CharField(max_length=6, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
