# Generated by Django 4.1.5 on 2023-01-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='use_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default=None, max_length=6, unique=True),
        ),
    ]
